#!/bin/bash
# init.sh - Full-stack Project Environment Setup
# Generated by IT Specialist Agent
# Stack: React (Frontend) + Node.js/Express (Backend) + PostgreSQL

set -e  # Exit on error

PROJECT_NAME="{{PROJECT_NAME}}"
FRONTEND_PORT="{{FRONTEND_PORT:-5173}}"
BACKEND_PORT="{{BACKEND_PORT:-3000}}"

echo "🚀 Setting up $PROJECT_NAME full-stack development environment..."

# Check prerequisites
check_prerequisites() {
    echo "📋 Checking prerequisites..."

    # Check Node.js
    if ! command -v node &> /dev/null; then
        echo "❌ Node.js is not installed"
        echo "   Install from: https://nodejs.org/"
        exit 1
    fi
    echo "✅ Node.js $(node --version)"

    # Check npm
    if ! command -v npm &> /dev/null; then
        echo "❌ npm is not installed"
        exit 1
    fi
    echo "✅ npm $(npm --version)"

    # Check Docker
    if ! command -v docker &> /dev/null; then
        echo "❌ Docker is not installed (required for database)"
        echo "   Install from: https://docker.com/get-started"
        exit 1
    fi
    echo "✅ Docker $(docker --version | cut -d' ' -f3 | tr -d ',')"

    # Check Docker Compose
    if ! command -v docker-compose &> /dev/null; then
        echo "⚠️  docker-compose not found, trying docker compose..."
        if ! docker compose version &> /dev/null; then
            echo "❌ Docker Compose not available"
            exit 1
        fi
        echo "✅ Docker Compose (plugin)"
    else
        echo "✅ Docker Compose $(docker-compose --version | cut -d' ' -f3 | tr -d ',')"
    fi
}

# Setup environment variables
setup_environment() {
    echo ""
    echo "🔧 Setting up environment variables..."

    # Backend .env
    if [ ! -f backend/.env ]; then
        if [ -f backend/.env.example ]; then
            cp backend/.env.example backend/.env
            echo "✅ Created backend/.env from template"
        else
            cat > backend/.env << 'EOF'
# Server
PORT=3000
NODE_ENV=development

# Database
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/{{PROJECT_NAME}}

# JWT
JWT_SECRET=change-this-secret-in-production
JWT_EXPIRES_IN=7d

# CORS
CORS_ORIGIN=http://localhost:5173
EOF
            echo "✅ Created backend/.env"
        fi
    else
        echo "✅ backend/.env already exists"
    fi

    # Frontend .env
    if [ ! -f frontend/.env ]; then
        if [ -f frontend/.env.example ]; then
            cp frontend/.env.example frontend/.env
            echo "✅ Created frontend/.env from template"
        else
            cat > frontend/.env << 'EOF'
VITE_API_URL=http://localhost:3000/api
VITE_APP_NAME={{PROJECT_NAME}}
EOF
            echo "✅ Created frontend/.env"
        fi
    else
        echo "✅ frontend/.env already exists"
    fi
}

# Install dependencies
install_dependencies() {
    echo ""
    echo "📦 Installing dependencies..."

    # Backend dependencies
    if [ -d backend ] && [ -f backend/package.json ]; then
        echo "Installing backend dependencies..."
        cd backend
        npm install
        cd ..
        echo "✅ Backend dependencies installed"
    fi

    # Frontend dependencies
    if [ -d frontend ] && [ -f frontend/package.json ]; then
        echo "Installing frontend dependencies..."
        cd frontend
        npm install
        cd ..
        echo "✅ Frontend dependencies installed"
    fi

    # Root dependencies (if monorepo)
    if [ -f package.json ]; then
        echo "Installing root dependencies..."
        npm install
        echo "✅ Root dependencies installed"
    fi
}

# Setup database
setup_database() {
    echo ""
    echo "🗄️  Setting up database with Docker..."

    if [ -f docker-compose.yml ]; then
        # Start database container
        docker-compose up -d
        echo "✅ Docker containers started"

        # Wait for PostgreSQL
        echo "⏳ Waiting for PostgreSQL to be ready..."
        sleep 10

        # Check if database is ready
        until docker exec $(docker ps | grep postgres | awk '{print $1}') pg_isready &> /dev/null; do
            echo "   Still waiting for database..."
            sleep 2
        done
        echo "✅ Database is ready"

        # Run migrations
        if [ -d backend ] && [ -f backend/package.json ]; then
            cd backend
            if npm run | grep -q "migrate"; then
                echo "Running database migrations..."
                npm run migrate
                echo "✅ Migrations complete"
            fi

            if npm run | grep -q "seed"; then
                echo "Seeding database..."
                npm run seed
                echo "✅ Database seeded with test data"
            fi
            cd ..
        fi
    else
        echo "❌ No docker-compose.yml found"
        exit 1
    fi
}

# Build projects
build_projects() {
    echo ""
    echo "🔨 Building projects..."

    # Build frontend
    if [ -d frontend ]; then
        cd frontend
        if npm run | grep -q "build"; then
            echo "Building frontend..."
            npm run build
            echo "✅ Frontend built"
        fi

        if npm run | grep -q "type-check"; then
            echo "Type checking frontend..."
            npm run type-check
            echo "✅ Frontend type check passed"
        fi
        cd ..
    fi

    # Build backend (if TypeScript)
    if [ -d backend ]; then
        cd backend
        if npm run | grep -q "build"; then
            echo "Building backend..."
            npm run build
            echo "✅ Backend built"
        fi
        cd ..
    fi
}

# Run tests
verify_setup() {
    echo ""
    echo "🧪 Running tests..."

    # Backend tests
    if [ -d backend ]; then
        cd backend
        if npm run | grep -q "test"; then
            echo "Running backend tests..."
            npm test
            echo "✅ Backend tests passed"
        fi
        cd ..
    fi

    # Frontend tests
    if [ -d frontend ]; then
        cd frontend
        if npm run | grep -q "test"; then
            echo "Running frontend tests..."
            npm test -- --run 2>/dev/null || npm test
            echo "✅ Frontend tests passed"
        fi
        cd ..
    fi
}

# Main execution
main() {
    echo "================================================"
    echo "  $PROJECT_NAME - Full-stack Setup"
    echo "================================================"
    echo ""

    check_prerequisites
    setup_environment
    install_dependencies
    setup_database
    build_projects
    verify_setup

    echo ""
    echo "================================================"
    echo "✅ Setup complete!"
    echo "================================================"
    echo ""
    echo "📝 Next steps:"
    echo ""
    echo "1. Edit environment files:"
    echo "   - backend/.env"
    echo "   - frontend/.env"
    echo ""
    echo "2. Start backend server:"
    echo "   cd backend && npm run dev"
    echo "   Backend will run at: http://localhost:$BACKEND_PORT"
    echo ""
    echo "3. Start frontend (in new terminal):"
    echo "   cd frontend && npm run dev"
    echo "   Frontend will run at: http://localhost:$FRONTEND_PORT"
    echo ""
    echo "4. Run tests:"
    echo "   Backend: cd backend && npm test"
    echo "   Frontend: cd frontend && npm test"
    echo ""
    echo "5. Access your application:"
    echo "   Frontend: http://localhost:$FRONTEND_PORT"
    echo "   Backend API: http://localhost:$BACKEND_PORT/api"
    echo "   Database: postgresql://localhost:5432/$PROJECT_NAME"
    echo ""
    echo "6. Stop database:"
    echo "   docker-compose down"
    echo ""
    echo "Happy coding! 🚀"
    echo ""
}

# Run main function
main
