#!/bin/bash
# init.sh - Node.js/React Project Environment Setup
# Generated by IT Specialist Agent

set -e  # Exit on error

PROJECT_NAME="{{PROJECT_NAME}}"
DEV_PORT="{{DEV_PORT:-5173}}"
API_PORT="{{API_PORT:-3000}}"

echo "🚀 Setting up $PROJECT_NAME development environment..."

# Check prerequisites
check_prerequisites() {
    echo "📋 Checking prerequisites..."

    # Check Node.js (minimum v18)
    if ! command -v node &> /dev/null; then
        echo "❌ Node.js is not installed"
        echo "   Install from: https://nodejs.org/ (LTS version recommended)"
        exit 1
    fi

    NODE_VERSION=$(node --version | cut -d'v' -f2 | cut -d'.' -f1)
    if [ "$NODE_VERSION" -lt 18 ]; then
        echo "❌ Node.js version 18+ required (found v$NODE_VERSION)"
        exit 1
    fi
    echo "✅ Node.js $(node --version)"

    # Check npm
    if ! command -v npm &> /dev/null; then
        echo "❌ npm is not installed"
        exit 1
    fi
    echo "✅ npm $(npm --version)"

    # Check Git
    if ! command -v git &> /dev/null; then
        echo "⚠️  Git not installed (recommended)"
    else
        echo "✅ Git $(git --version | head -1)"
    fi
}

# Setup environment variables
setup_environment() {
    echo ""
    echo "🔧 Setting up environment variables..."

    if [ ! -f .env ]; then
        if [ -f .env.example ]; then
            cp .env.example .env
            echo "✅ Created .env from template"
            echo ""
            echo "⚠️  Required: Edit .env and configure these variables:"
            grep -E "^VITE_|^REACT_APP_" .env.example 2>/dev/null | sed 's/=.*//' | sed 's/^/   - /' || true
            grep -E "^DATABASE_URL|^API_KEY|^JWT_SECRET" .env.example 2>/dev/null | sed 's/=.*//' | sed 's/^/   - /' || true
            echo ""
        else
            echo "⚠️  No .env.example found - creating basic .env"
            cat > .env << 'EOF'
# Frontend environment variables (Vite)
VITE_API_URL=http://localhost:3000/api
VITE_APP_NAME={{PROJECT_NAME}}

# Development
NODE_ENV=development
EOF
            echo "✅ Created basic .env file"
        fi
    else
        echo "✅ .env already exists"
    fi
}

# Install dependencies
install_dependencies() {
    echo ""
    echo "📦 Installing dependencies..."

    # Install root dependencies
    if [ -f package.json ]; then
        echo "Installing npm packages..."
        npm install
        echo "✅ Dependencies installed"
    fi

    # Install backend dependencies if separate
    if [ -d backend ] && [ -f backend/package.json ]; then
        echo "Installing backend dependencies..."
        cd backend
        npm install
        cd ..
        echo "✅ Backend dependencies installed"
    fi
}

# Setup database (if using Docker)
setup_database() {
    echo ""
    echo "🗄️  Setting up database..."

    # Check for Docker Compose
    if [ -f docker-compose.yml ]; then
        if command -v docker &> /dev/null; then
            echo "Starting Docker containers..."
            docker-compose up -d
            echo "✅ Docker containers started"

            # Wait for database
            echo "⏳ Waiting for database to be ready (10 seconds)..."
            sleep 10
            echo "✅ Database should be ready"
        else
            echo "⚠️  Docker not installed - skip database setup"
            echo "   Install Docker from: https://docker.com/get-started"
        fi
    else
        echo "ℹ️  No docker-compose.yml - skipping database setup"
    fi

    # Run migrations if available
    if [ -f package.json ]; then
        if npm run | grep -q "migrate"; then
            echo "Running database migrations..."
            npm run migrate
            echo "✅ Migrations complete"
        fi

        if npm run | grep -q "seed"; then
            echo "Seeding database with test data..."
            npm run seed
            echo "✅ Database seeded"
        fi
    fi
}

# Build project
build_project() {
    echo ""
    echo "🔨 Building project..."

    if [ -f package.json ]; then
        # Check if build script exists
        if npm run | grep -q "build"; then
            echo "Running build..."
            npm run build
            echo "✅ Build successful"
        else
            echo "ℹ️  No build script - skipping"
        fi

        # TypeScript type checking
        if npm run | grep -q "type-check"; then
            echo "Running TypeScript type check..."
            npm run type-check
            echo "✅ Type check passed"
        fi
    fi
}

# Run tests
verify_setup() {
    echo ""
    echo "🧪 Verifying setup with tests..."

    if [ -f package.json ]; then
        if npm run | grep -q "\"test\""; then
            echo "Running test suite..."
            npm test -- --run 2>/dev/null || npm test
            echo "✅ Tests passed"
        else
            echo "⚠️  No test script configured"
        fi
    fi
}

# Main execution
main() {
    echo "================================================"
    echo "  $PROJECT_NAME - React/Node.js Setup"
    echo "================================================"
    echo ""

    check_prerequisites
    setup_environment
    install_dependencies
    setup_database
    build_project
    verify_setup

    echo ""
    echo "================================================"
    echo "✅ Setup complete!"
    echo "================================================"
    echo ""
    echo "📝 Next steps:"
    echo ""
    echo "1. Edit .env file with your configuration"
    echo "2. Start development server:"
    echo "   npm run dev"
    echo ""
    echo "3. Visit your app:"
    echo "   Frontend: http://localhost:$DEV_PORT"
    if [ -d backend ]; then
        echo "   Backend:  http://localhost:$API_PORT"
    fi
    echo ""
    echo "4. Run tests:"
    echo "   npm test"
    echo ""
    echo "Happy coding! 🚀"
    echo ""
}

# Run main function
main
