#!/bin/bash
# init.sh - Python/Django Project Environment Setup
# Generated by IT Specialist Agent

set -e  # Exit on error

PROJECT_NAME="{{PROJECT_NAME}}"
PYTHON_VERSION="{{PYTHON_VERSION:-3.11}}"

echo "🚀 Setting up $PROJECT_NAME development environment..."

# Check prerequisites
check_prerequisites() {
    echo "📋 Checking prerequisites..."

    # Check Python
    if ! command -v python3 &> /dev/null; then
        echo "❌ Python 3 is not installed"
        echo "   Install from: https://python.org/downloads/"
        exit 1
    fi
    echo "✅ Python $(python3 --version)"

    # Check pip
    if ! command -v pip3 &> /dev/null; then
        echo "❌ pip is not installed"
        exit 1
    fi
    echo "✅ pip $(pip3 --version | cut -d' ' -f2)"

    # Check if venv module available
    if ! python3 -m venv --help &> /dev/null; then
        echo "❌ Python venv module not available"
        echo "   Install: apt-get install python3-venv (Ubuntu/Debian)"
        exit 1
    fi
    echo "✅ venv module available"

    # Check PostgreSQL client (optional)
    if command -v psql &> /dev/null; then
        echo "✅ PostgreSQL client $(psql --version | cut -d' ' -f3)"
    else
        echo "ℹ️  PostgreSQL client not installed (optional)"
    fi
}

# Setup virtual environment
setup_virtualenv() {
    echo ""
    echo "🐍 Setting up Python virtual environment..."

    if [ ! -d venv ]; then
        python3 -m venv venv
        echo "✅ Virtual environment created"
    else
        echo "✅ Virtual environment already exists"
    fi

    # Activate virtual environment
    source venv/bin/activate
    echo "✅ Virtual environment activated"

    # Upgrade pip
    pip install --upgrade pip
    echo "✅ pip upgraded"
}

# Setup environment variables
setup_environment() {
    echo ""
    echo "🔧 Setting up environment variables..."

    if [ ! -f .env ]; then
        if [ -f .env.example ]; then
            cp .env.example .env
            echo "✅ Created .env from template"
            echo ""
            echo "⚠️  Required: Edit .env and configure these variables:"
            grep -E "^DATABASE_URL|^SECRET_KEY|^DEBUG" .env.example 2>/dev/null | sed 's/=.*//' | sed 's/^/   - /' || true
            echo ""
        else
            echo "⚠️  No .env.example found - creating basic .env"
            cat > .env << 'EOF'
# Django settings
DEBUG=True
SECRET_KEY=django-insecure-change-this-in-production
ALLOWED_HOSTS=localhost,127.0.0.1

# Database
DATABASE_URL=postgresql://user:password@localhost:5432/{{PROJECT_NAME}}

# Email (development)
EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
EOF
            echo "✅ Created basic .env file"
        fi
    else
        echo "✅ .env already exists"
    fi
}

# Install dependencies
install_dependencies() {
    echo ""
    echo "📦 Installing Python dependencies..."

    # Ensure venv is activated
    source venv/bin/activate

    if [ -f requirements.txt ]; then
        pip install -r requirements.txt
        echo "✅ Dependencies installed from requirements.txt"
    fi

    if [ -f requirements/development.txt ]; then
        pip install -r requirements/development.txt
        echo "✅ Development dependencies installed"
    fi

    # Install development tools
    pip install black flake8 pytest pytest-django
    echo "✅ Development tools installed"
}

# Setup database
setup_database() {
    echo ""
    echo "🗄️  Setting up database..."

    # Ensure venv is activated
    source venv/bin/activate

    # Start Docker database if docker-compose exists
    if [ -f docker-compose.yml ]; then
        if command -v docker &> /dev/null; then
            echo "Starting Docker containers..."
            docker-compose up -d
            echo "✅ Docker containers started"

            # Wait for database
            echo "⏳ Waiting for database (15 seconds)..."
            sleep 15

            # Test PostgreSQL connection
            if docker exec $(docker ps | grep postgres | awk '{print $1}') pg_isready &> /dev/null; then
                echo "✅ Database is ready"
            else
                echo "⚠️  Database might not be ready yet"
            fi
        else
            echo "⚠️  Docker not installed - manual database setup required"
        fi
    fi

    # Run Django migrations
    if [ -f manage.py ]; then
        echo "Running database migrations..."
        python manage.py migrate
        echo "✅ Migrations complete"

        # Create superuser if needed (non-interactive)
        echo "Checking for superuser..."
        python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); print('Superuser exists' if User.objects.filter(is_superuser=True).exists() else 'No superuser')" | grep -q "No superuser" && {
            echo ""
            echo "⚠️  No superuser found. Create one with:"
            echo "   python manage.py createsuperuser"
            echo ""
        } || echo "✅ Superuser exists"

        # Load fixtures if available
        if [ -d fixtures ]; then
            echo "Loading fixtures..."
            for fixture in fixtures/*.json; do
                if [ -f "$fixture" ]; then
                    python manage.py loaddata "$fixture"
                fi
            done
            echo "✅ Fixtures loaded"
        fi
    fi
}

# Run tests
verify_setup() {
    echo ""
    echo "🧪 Verifying setup with tests..."

    # Ensure venv is activated
    source venv/bin/activate

    if [ -f manage.py ]; then
        echo "Running Django tests..."
        python manage.py test --verbosity=1
        echo "✅ Tests passed"
    elif [ -f pytest.ini ] || [ -f setup.cfg ]; then
        echo "Running pytest..."
        pytest
        echo "✅ Tests passed"
    else
        echo "⚠️  No test configuration found"
    fi
}

# Collect static files
collect_static() {
    echo ""
    echo "📦 Collecting static files..."

    # Ensure venv is activated
    source venv/bin/activate

    if [ -f manage.py ]; then
        python manage.py collectstatic --noinput
        echo "✅ Static files collected"
    fi
}

# Main execution
main() {
    echo "================================================"
    echo "  $PROJECT_NAME - Django Setup"
    echo "================================================"
    echo ""

    check_prerequisites
    setup_virtualenv
    setup_environment
    install_dependencies
    setup_database
    collect_static
    verify_setup

    echo ""
    echo "================================================"
    echo "✅ Setup complete!"
    echo "================================================"
    echo ""
    echo "📝 Next steps:"
    echo ""
    echo "1. Activate virtual environment:"
    echo "   source venv/bin/activate"
    echo ""
    echo "2. Edit .env file with your configuration"
    echo ""
    echo "3. Create superuser (if needed):"
    echo "   python manage.py createsuperuser"
    echo ""
    echo "4. Start development server:"
    echo "   python manage.py runserver"
    echo ""
    echo "5. Visit your app:"
    echo "   http://localhost:8000"
    echo "   Admin: http://localhost:8000/admin"
    echo ""
    echo "6. Run tests:"
    echo "   python manage.py test"
    echo ""
    echo "Happy coding! 🐍"
    echo ""
}

# Run main function
main
